// Auto-generated from stdlib.scm - do not edit
static const char stdlib_scm[] =
    "; R3RS Standard Library\n"
    "; This file is loaded automatically on startup\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Let forms as macros\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; letrec - recursive binding (must be defined first, uses only lambda)\n"
    "(define-syntax letrec\n"
    "  (syntax-rules ()\n"
    "    ((letrec ((var val) ...) body ...)\n"
    "     ((lambda (var ...)\n"
    "        (set! var val) ...\n"
    "        body ...)\n"
    "      #f ...))))\n"
    "\n"
    "; let - parallel binding (named let uses letrec defined above)\n"
    "(define-syntax let\n"
    "  (syntax-rules ()\n"
    "    ((let ((var val) ...) body ...)\n"
    "     ((lambda (var ...) body ...) val ...))\n"
    "    ; Named let\n"
    "    ((let name ((var val) ...) body ...)\n"
    "     (letrec ((name (lambda (var ...) body ...)))\n"
    "       (name val ...)))))\n"
    "\n"
    "; let* - sequential binding (uses lambda directly)\n"
    "; Need explicit patterns for different binding counts due to ellipsis "
    "limitations\n"
    "(define-syntax let*\n"
    "  (syntax-rules ()\n"
    "    ((let* () body ...)\n"
    "     (begin body ...))\n"
    "    ((let* ((var val) . more-bindings) body ...)\n"
    "     ((lambda (var)\n"
    "        (let* more-bindings body ...))\n"
    "      val))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Case and Do macros\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; case - multi-way branch\n"
    "(define-syntax case\n"
    "  (syntax-rules (else)\n"
    "    ((case key (else result ...))\n"
    "     (begin result ...))\n"
    "    ((case key ((atoms ...) result ...))\n"
    "     (if (memv key '(atoms ...))\n"
    "         (begin result ...)))\n"
    "    ((case key ((atoms ...) result ...) clause ...)\n"
    "     (if (memv key '(atoms ...))\n"
    "         (begin result ...)\n"
    "         (case key clause ...)))))\n"
    "\n"
    "; do - iteration\n"
    "(define-syntax do\n"
    "  (syntax-rules ()\n"
    "    ((do ((var init step ...) ...)\n"
    "         (test expr ...)\n"
    "       command ...)\n"
    "     (letrec ((loop\n"
    "               (lambda (var ...)\n"
    "                 (if test\n"
    "                     (begin #f expr ...)\n"
    "                     (begin\n"
    "                       command ...\n"
    "                       (loop (do-step var step ...) ...))))))\n"
    "       (loop init ...)))\n"
    "    ))\n"
    "\n"
    "(define-syntax do-step\n"
    "  (syntax-rules ()\n"
    "    ((do-step var) var)\n"
    "    ((do-step var step) step)))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; List accessors (compositions of car/cdr)\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "(define (caar x) (car (car x)))\n"
    "(define (cadr x) (car (cdr x)))\n"
    "(define (cdar x) (cdr (car x)))\n"
    "(define (cddr x) (cdr (cdr x)))\n"
    "\n"
    "(define (caaar x) (car (car (car x))))\n"
    "(define (caadr x) (car (car (cdr x))))\n"
    "(define (cadar x) (car (cdr (car x))))\n"
    "(define (caddr x) (car (cdr (cdr x))))\n"
    "(define (cdaar x) (cdr (car (car x))))\n"
    "(define (cdadr x) (cdr (car (cdr x))))\n"
    "(define (cddar x) (cdr (cdr (car x))))\n"
    "(define (cdddr x) (cdr (cdr (cdr x))))\n"
    "\n"
    "(define (caaaar x) (car (car (car (car x)))))\n"
    "(define (caaadr x) (car (car (car (cdr x)))))\n"
    "(define (caadar x) (car (car (cdr (car x)))))\n"
    "(define (caaddr x) (car (car (cdr (cdr x)))))\n"
    "(define (cadaar x) (car (cdr (car (car x)))))\n"
    "(define (cadadr x) (car (cdr (car (cdr x)))))\n"
    "(define (caddar x) (car (cdr (cdr (car x)))))\n"
    "(define (cadddr x) (car (cdr (cdr (cdr x)))))\n"
    "(define (cdaaar x) (cdr (car (car (car x)))))\n"
    "(define (cdaadr x) (cdr (car (car (cdr x)))))\n"
    "(define (cdadar x) (cdr (car (cdr (car x)))))\n"
    "(define (cdaddr x) (cdr (car (cdr (cdr x)))))\n"
    "(define (cddaar x) (cdr (cdr (car (car x)))))\n"
    "(define (cddadr x) (cdr (cdr (car (cdr x)))))\n"
    "(define (cdddar x) (cdr (cdr (cdr (car x)))))\n"
    "(define (cddddr x) (cdr (cdr (cdr (cdr x)))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; List utilities\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "(define (list-ref lst k)\n"
    "  (if (= k 0)\n"
    "      (car lst)\n"
    "      (list-ref (cdr lst) (- k 1))))\n"
    "\n"
    "(define (list-tail lst k)\n"
    "  (if (= k 0)\n"
    "      lst\n"
    "      (list-tail (cdr lst) (- k 1))))\n"
    "\n"
    "; Membership functions\n"
    "(define (memq obj lst)\n"
    "  (cond ((null? lst) #f)\n"
    "        ((eq? obj (car lst)) lst)\n"
    "        (else (memq obj (cdr lst)))))\n"
    "\n"
    "(define (memv obj lst)\n"
    "  (cond ((null? lst) #f)\n"
    "        ((eqv? obj (car lst)) lst)\n"
    "        (else (memv obj (cdr lst)))))\n"
    "\n"
    "(define (member obj lst)\n"
    "  (cond ((null? lst) #f)\n"
    "        ((equal? obj (car lst)) lst)\n"
    "        (else (member obj (cdr lst)))))\n"
    "\n"
    "; Association list functions\n"
    "(define (assq obj alist)\n"
    "  (cond ((null? alist) #f)\n"
    "        ((eq? obj (caar alist)) (car alist))\n"
    "        (else (assq obj (cdr alist)))))\n"
    "\n"
    "(define (assv obj alist)\n"
    "  (cond ((null? alist) #f)\n"
    "        ((eqv? obj (caar alist)) (car alist))\n"
    "        (else (assv obj (cdr alist)))))\n"
    "\n"
    "(define (assoc obj alist)\n"
    "  (cond ((null? alist) #f)\n"
    "        ((equal? obj (caar alist)) (car alist))\n"
    "        (else (assoc obj (cdr alist)))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Numeric predicates\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "(define (zero? n) (= n 0))\n"
    "(define (positive? n) (> n 0))\n"
    "(define (negative? n) (< n 0))\n"
    "(define (odd? n) (= (remainder n 2) 1))\n"
    "(define (even? n) (= (remainder n 2) 0))\n"
    "\n"
    "(define (max x . rest)\n"
    "  (if (null? rest)\n"
    "      x\n"
    "      (let ((m (apply max rest)))\n"
    "        (if (> x m) x m))))\n"
    "\n"
    "(define (min x . rest)\n"
    "  (if (null? rest)\n"
    "      x\n"
    "      (let ((m (apply min rest)))\n"
    "        (if (< x m) x m))))\n"
    "\n"
    "(define (gcd . args)\n"
    "  (define (gcd2 a b)\n"
    "    (if (= b 0)\n"
    "        (abs a)\n"
    "        (gcd2 b (remainder a b))))\n"
    "  (if (null? args)\n"
    "      0\n"
    "      (let loop ((result (car args)) (rest (cdr args)))\n"
    "        (if (null? rest)\n"
    "            (abs result)\n"
    "            (loop (gcd2 result (car rest)) (cdr rest))))))\n"
    "\n"
    "(define (lcm . args)\n"
    "  (define (lcm2 a b)\n"
    "    (if (or (= a 0) (= b 0))\n"
    "        0\n"
    "        (abs (quotient (* a b) (gcd a b)))))\n"
    "  (if (null? args)\n"
    "      1\n"
    "      (let loop ((result (car args)) (rest (cdr args)))\n"
    "        (if (null? rest)\n"
    "            (abs result)\n"
    "            (loop (lcm2 result (car rest)) (cdr rest))))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Higher-order functions\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "(define (map proc lst . lsts)\n"
    "  (if (null? lsts)\n"
    "      ; Single list case\n"
    "      (if (null? lst)\n"
    "          '()\n"
    "          (cons (proc (car lst))\n"
    "                (map proc (cdr lst))))\n"
    "      ; Multiple lists case\n"
    "      (if (null? lst)\n"
    "          '()\n"
    "          (cons (apply proc (car lst) (map car lsts))\n"
    "                (apply map proc (cdr lst) (map cdr lsts))))))\n"
    "\n"
    "(define (for-each proc lst . lsts)\n"
    "  (if (null? lsts)\n"
    "      ; Single list case\n"
    "      (if (not (null? lst))\n"
    "          (begin\n"
    "            (proc (car lst))\n"
    "            (for-each proc (cdr lst))))\n"
    "      ; Multiple lists case\n"
    "      (if (not (null? lst))\n"
    "          (begin\n"
    "            (apply proc (car lst) (map car lsts))\n"
    "            (apply for-each proc (cdr lst) (map cdr lsts))))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional utilities\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; not is already a primitive, but define it for completeness\n"
    "; (define (not x) (if x #f #t))\n"
    "\n"
    "; Force/delay (simple implementation)\n"
    "(define-syntax delay\n"
    "  (syntax-rules ()\n"
    "    ((delay expr)\n"
    "     (let ((forced #f) (value #f))\n"
    "       (lambda ()\n"
    "         (if forced\n"
    "             value\n"
    "             (begin\n"
    "               (set! value expr)\n"
    "               (set! forced #t)\n"
    "               value)))))))\n"
    "\n"
    "(define (force promise)\n"
    "  (promise))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; File I/O forms (R3RS)\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "(define (call-with-input-file filename proc)\n"
    "  (let ((port (open-input-file filename)))\n"
    "    (let ((result (proc port)))\n"
    "      (close-input-port port)\n"
    "      result)))\n"
    "\n"
    "(define (call-with-output-file filename proc)\n"
    "  (let ((port (open-output-file filename)))\n"
    "    (let ((result (proc port)))\n"
    "      (close-output-port port)\n"
    "      result)))\n"
    "\n"
    "; with-input-from-file temporarily redirects current-input-port\n"
    "; Note: This is a simplified implementation\n"
    "(define (with-input-from-file filename thunk)\n"
    "  (let ((port (open-input-file filename)))\n"
    "    (let ((result (thunk)))\n"
    "      (close-input-port port)\n"
    "      result)))\n"
    "\n"
    "; with-output-to-file temporarily redirects current-output-port\n"
    "; Note: This is a simplified implementation\n"
    "(define (with-output-to-file filename thunk)\n"
    "  (let ((port (open-output-file filename)))\n"
    "    (let ((result (thunk)))\n"
    "      (close-output-port port)\n"
    "      result)))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; String port convenience functions\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; Call proc with a fresh output string port, return accumulated string\n"
    "(define (call-with-output-string proc)\n"
    "  (let ((port (open-output-string)))\n"
    "    (proc port)\n"
    "    (get-output-string port)))\n"
    "\n"
    "; Call proc with an input string port reading from str\n"
    "(define (call-with-input-string str proc)\n"
    "  (let ((port (open-input-string str)))\n"
    "    (proc port)))\n"
    "\n"
    "; Execute thunk with output captured to a string\n"
    "(define-syntax with-output-to-string\n"
    "  (syntax-rules ()\n"
    "    ((with-output-to-string body ...)\n"
    "     (let ((port (open-output-string)))\n"
    "       (let ((write-to-port (lambda args\n"
    "                              (if (null? args)\n"
    "                                  (newline port)\n"
    "                                  (display (car args) port)))))\n"
    "         body ...)\n"
    "       (get-output-string port)))))\n"
    "\n"
    "; Execute thunk with input coming from a string\n"
    "(define-syntax with-input-from-string\n"
    "  (syntax-rules ()\n"
    "    ((with-input-from-string str body ...)\n"
    "     (let ((port (open-input-string str)))\n"
    "       body ...))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; List Processing Utilities (SRFI-1 style)\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; filter - return list of elements satisfying predicate\n"
    "(define (filter pred lst)\n"
    "  (cond ((null? lst) '())\n"
    "        ((pred (car lst))\n"
    "         (cons (car lst) (filter pred (cdr lst))))\n"
    "        (else (filter pred (cdr lst)))))\n"
    "\n"
    "; remove - return list of elements NOT satisfying predicate\n"
    "(define (remove pred lst)\n"
    "  (filter (lambda (x) (not (pred x))) lst))\n"
    "\n"
    "; find - return first element satisfying predicate, or #f\n"
    "(define (find pred lst)\n"
    "  (cond ((null? lst) #f)\n"
    "        ((pred (car lst)) (car lst))\n"
    "        (else (find pred (cdr lst)))))\n"
    "\n"
    "; any - return #t if any element satisfies predicate\n"
    "(define (any pred lst)\n"
    "  (cond ((null? lst) #f)\n"
    "        ((pred (car lst)) #t)\n"
    "        (else (any pred (cdr lst)))))\n"
    "\n"
    "; every - return #t if all elements satisfy predicate\n"
    "(define (every pred lst)\n"
    "  (cond ((null? lst) #t)\n"
    "        ((not (pred (car lst))) #f)\n"
    "        (else (every pred (cdr lst)))))\n"
    "\n"
    "; count - count elements satisfying predicate\n"
    "(define (count pred lst)\n"
    "  (let loop ((lst lst) (n 0))\n"
    "    (cond ((null? lst) n)\n"
    "          ((pred (car lst)) (loop (cdr lst) (+ n 1)))\n"
    "          (else (loop (cdr lst) n)))))\n"
    "\n"
    "; fold-left (reduce) - left-associative fold\n"
    "(define (fold proc init lst)\n"
    "  (if (null? lst)\n"
    "      init\n"
    "      (fold proc (proc (car lst) init) (cdr lst))))\n"
    "\n"
    "; fold-right - right-associative fold\n"
    "(define (fold-right proc init lst)\n"
    "  (if (null? lst)\n"
    "      init\n"
    "      (proc (car lst) (fold-right proc init (cdr lst)))))\n"
    "\n"
    "; reduce - like fold but uses first element as initial value\n"
    "(define (reduce proc lst)\n"
    "  (if (null? lst)\n"
    "      (error \"reduce: empty list\")\n"
    "      (fold proc (car lst) (cdr lst))))\n"
    "\n"
    "; take - return first n elements of list\n"
    "(define (take n lst)\n"
    "  (if (or (= n 0) (null? lst))\n"
    "      '()\n"
    "      (cons (car lst) (take (- n 1) (cdr lst)))))\n"
    "\n"
    "; drop - return list without first n elements\n"
    "(define (drop n lst)\n"
    "  (if (or (= n 0) (null? lst))\n"
    "      lst\n"
    "      (drop (- n 1) (cdr lst))))\n"
    "\n"
    "; partition - split list into two lists based on predicate\n"
    "(define (partition pred lst)\n"
    "  (let loop ((lst lst) (yes '()) (no '()))\n"
    "    (cond ((null? lst) (list (reverse yes) (reverse no)))\n"
    "          ((pred (car lst)) (loop (cdr lst) (cons (car lst) yes) no))\n"
    "          (else (loop (cdr lst) yes (cons (car lst) no))))))\n"
    "\n"
    "; zip - combine corresponding elements of two lists\n"
    "(define (zip lst1 lst2)\n"
    "  (if (or (null? lst1) (null? lst2))\n"
    "      '()\n"
    "      (cons (list (car lst1) (car lst2))\n"
    "            (zip (cdr lst1) (cdr lst2)))))\n"
    "\n"
    "; flatten - flatten nested list structure\n"
    "(define (flatten lst)\n"
    "  (cond ((null? lst) '())\n"
    "        ((not (pair? lst)) (list lst))\n"
    "        (else (append (flatten (car lst)) (flatten (cdr lst))))))\n"
    "\n"
    "; last - return last element of list\n"
    "(define (last lst)\n"
    "  (if (null? (cdr lst))\n"
    "      (car lst)\n"
    "      (last (cdr lst))))\n"
    "\n"
    "; iota - generate list of integers [0, n)\n"
    "(define (iota n)\n"
    "  (let loop ((i (- n 1)) (acc '()))\n"
    "    (if (< i 0)\n"
    "        acc\n"
    "        (loop (- i 1) (cons i acc)))))\n"
    "\n"
    "; range - generate list of integers [start, end)\n"
    "(define (range start end)\n"
    "  (let loop ((i (- end 1)) (acc '()))\n"
    "    (if (< i start)\n"
    "        acc\n"
    "        (loop (- i 1) (cons i acc)))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Constructors\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; xcons - like cons but with reversed arguments\n"
    "(define (xcons d a) (cons a d))\n"
    "\n"
    "; cons* - like list but last arg is tail\n"
    "(define (cons* first . rest)\n"
    "  (if (null? rest)\n"
    "      first\n"
    "      (cons first (apply cons* rest))))\n"
    "\n"
    "; make-list - create list of n elements, optionally filled with fill\n"
    "(define (make-list n . fill)\n"
    "  (let ((f (if (null? fill) #f (car fill))))\n"
    "    (let loop ((n n) (acc '()))\n"
    "      (if (<= n 0)\n"
    "          acc\n"
    "          (loop (- n 1) (cons f acc))))))\n"
    "\n"
    "; list-tabulate - create list by calling init-proc on indices 0..n-1\n"
    "(define (list-tabulate n init-proc)\n"
    "  (let loop ((i (- n 1)) (acc '()))\n"
    "    (if (< i 0)\n"
    "        acc\n"
    "        (loop (- i 1) (cons (init-proc i) acc)))))\n"
    "\n"
    "; list-copy - shallow copy of list\n"
    "(define (list-copy lst)\n"
    "  (if (null? lst)\n"
    "      '()\n"
    "      (cons (car lst) (list-copy (cdr lst)))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Predicates\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; not-pair? - true if x is not a pair\n"
    "(define (not-pair? x) (not (pair? x)))\n"
    "\n"
    "; null-list? - like null? but signals error on improper list\n"
    "(define (null-list? lst)\n"
    "  (cond ((null? lst) #t)\n"
    "        ((pair? lst) #f)\n"
    "        (else (error \"null-list?: not a proper list\"))))\n"
    "\n"
    "; proper-list? - true if x is a proper list (finite, nil-terminated)\n"
    "; Uses tortoise-and-hare algorithm for cycle detection\n"
    "(define (proper-list? x)\n"
    "  (let loop ((fast x) (slow x) (first? #t))\n"
    "    (cond ((null? fast) #t)\n"
    "          ((not (pair? fast)) #f)\n"
    "          ((null? (cdr fast)) #t)\n"
    "          ((not (pair? (cdr fast))) #f)\n"
    "          ((and (not first?) (eq? fast slow)) #f)  ; cycle detected\n"
    "          (else (loop (cddr fast) (cdr slow) #f)))))\n"
    "\n"
    "; list? - alias for proper-list?\n"
    "(define list? proper-list?)\n"
    "\n"
    "; dotted-list? - true if x is a finite, non-nil-terminated list\n"
    "(define (dotted-list? x)\n"
    "  (let loop ((fast x) (slow x) (first? #t))\n"
    "    (cond ((null? fast) #f)\n"
    "          ((not (pair? fast)) #t)\n"
    "          ((null? (cdr fast)) #f)\n"
    "          ((not (pair? (cdr fast))) #t)\n"
    "          ((and (not first?) (eq? fast slow)) #f)  ; cycle - not dotted\n"
    "          (else (loop (cddr fast) (cdr slow) #f)))))\n"
    "\n"
    "; list= - compare lists element-wise using elt=\n"
    "(define (list= elt= . lists)\n"
    "  (or (null? lists)\n"
    "      (null? (cdr lists))\n"
    "      (let loop ((lists lists))\n"
    "        (or (null? (cdr lists))\n"
    "            (let ((a (car lists)) (b (cadr lists)))\n"
    "              (and (let cmp ((a a) (b b))\n"
    "                     (cond ((null? a) (null? b))\n"
    "                           ((null? b) #f)\n"
    "                           ((elt= (car a) (car b)) (cmp (cdr a) (cdr "
    "b)))\n"
    "                           (else #f)))\n"
    "                   (loop (cdr lists))))))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Selectors\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; first through tenth - positional accessors\n"
    "(define (first x) (car x))\n"
    "(define (second x) (cadr x))\n"
    "(define (third x) (caddr x))\n"
    "(define (fourth x) (cadddr x))\n"
    "(define (fifth x) (car (cddddr x)))\n"
    "(define (sixth x) (cadr (cddddr x)))\n"
    "(define (seventh x) (caddr (cddddr x)))\n"
    "(define (eighth x) (cadddr (cddddr x)))\n"
    "(define (ninth x) (car (cddddr (cddddr x))))\n"
    "(define (tenth x) (cadr (cddddr (cddddr x))))\n"
    "\n"
    "; car+cdr - return both car and cdr as multiple values\n"
    "(define (car+cdr pair)\n"
    "  (values (car pair) (cdr pair)))\n"
    "\n"
    "; take-right - return last n elements\n"
    "(define (take-right lst n)\n"
    "  (let ((len (length lst)))\n"
    "    (drop (- len n) lst)))\n"
    "\n"
    "; drop-right - return all but last n elements\n"
    "(define (drop-right lst n)\n"
    "  (let ((len (length lst)))\n"
    "    (take (- len n) lst)))\n"
    "\n"
    "; split-at - split list at index, return two lists\n"
    "(define (split-at lst n)\n"
    "  (values (take n lst) (drop n lst)))\n"
    "\n"
    "; last-pair - return last pair of list\n"
    "(define (last-pair lst)\n"
    "  (if (null? (cdr lst))\n"
    "      lst\n"
    "      (last-pair (cdr lst))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Miscellaneous\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; concatenate - append all lists in list-of-lists\n"
    "(define (concatenate lists)\n"
    "  (apply append lists))\n"
    "\n"
    "; append-reverse - (append (reverse rev-head) tail)\n"
    "(define (append-reverse rev-head tail)\n"
    "  (if (null? rev-head)\n"
    "      tail\n"
    "      (append-reverse (cdr rev-head) (cons (car rev-head) tail))))\n"
    "\n"
    "; unzip1 - extract first elements from list of lists\n"
    "(define (unzip1 lists)\n"
    "  (map car lists))\n"
    "\n"
    "; unzip2 - extract first two elements from list of lists\n"
    "(define (unzip2 lists)\n"
    "  (values (map car lists) (map cadr lists)))\n"
    "\n"
    "; unzip3 - extract first three elements\n"
    "(define (unzip3 lists)\n"
    "  (values (map car lists) (map cadr lists) (map caddr lists)))\n"
    "\n"
    "; unzip4 - extract first four elements\n"
    "(define (unzip4 lists)\n"
    "  (values (map car lists) (map cadr lists) (map caddr lists) (map cadddr "
    "lists)))\n"
    "\n"
    "; unzip5 - extract first five elements\n"
    "(define (unzip5 lists)\n"
    "  (values (map car lists) (map cadr lists) (map caddr lists)\n"
    "          (map cadddr lists) (map fifth lists)))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Fold/Unfold/Map\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; pair-fold - like fold but proc receives pairs, not elements\n"
    "(define (pair-fold proc init lst)\n"
    "  (if (null? lst)\n"
    "      init\n"
    "      (let ((tail (cdr lst)))\n"
    "        (pair-fold proc (proc lst init) tail))))\n"
    "\n"
    "; pair-fold-right - like fold-right but proc receives pairs\n"
    "(define (pair-fold-right proc init lst)\n"
    "  (if (null? lst)\n"
    "      init\n"
    "      (proc lst (pair-fold-right proc init (cdr lst)))))\n"
    "\n"
    "; reduce-right - like reduce but right-associative\n"
    "(define (reduce-right proc init lst)\n"
    "  (if (null? lst)\n"
    "      init\n"
    "      (let loop ((lst lst))\n"
    "        (if (null? (cdr lst))\n"
    "            (car lst)\n"
    "            (proc (car lst) (loop (cdr lst)))))))\n"
    "\n"
    "; unfold - generate list from seed using p, f, g\n"
    "(define (unfold p f g seed . maybe-tail-gen)\n"
    "  (let ((tail-gen (if (null? maybe-tail-gen) (lambda (x) '()) (car "
    "maybe-tail-gen))))\n"
    "    (let loop ((seed seed))\n"
    "      (if (p seed)\n"
    "          (tail-gen seed)\n"
    "          (cons (f seed) (loop (g seed)))))))\n"
    "\n"
    "; unfold-right - like unfold but builds list right-to-left\n"
    "(define (unfold-right p f g seed . maybe-tail)\n"
    "  (let ((tail (if (null? maybe-tail) '() (car maybe-tail))))\n"
    "    (let loop ((seed seed) (acc tail))\n"
    "      (if (p seed)\n"
    "          acc\n"
    "          (loop (g seed) (cons (f seed) acc))))))\n"
    "\n"
    "; append-map - map then append results\n"
    "(define (append-map proc lst . lsts)\n"
    "  (apply append (apply map proc lst lsts)))\n"
    "\n"
    "; filter-map - map and filter in one pass\n"
    "(define (filter-map proc lst)\n"
    "  (let loop ((lst lst) (acc '()))\n"
    "    (if (null? lst)\n"
    "        (reverse acc)\n"
    "        (let ((result (proc (car lst))))\n"
    "          (loop (cdr lst) (if result (cons result acc) acc))))))\n"
    "\n"
    "; pair-for-each - like for-each but proc receives pairs\n"
    "(define (pair-for-each proc lst)\n"
    "  (if (not (null? lst))\n"
    "      (begin\n"
    "        (proc lst)\n"
    "        (pair-for-each proc (cdr lst)))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Searching\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; find-tail - return tail of list starting at first match\n"
    "(define (find-tail pred lst)\n"
    "  (cond ((null? lst) #f)\n"
    "        ((pred (car lst)) lst)\n"
    "        (else (find-tail pred (cdr lst)))))\n"
    "\n"
    "; list-index - return index of first element satisfying pred\n"
    "(define (list-index pred lst)\n"
    "  (let loop ((lst lst) (i 0))\n"
    "    (cond ((null? lst) #f)\n"
    "          ((pred (car lst)) i)\n"
    "          (else (loop (cdr lst) (+ i 1))))))\n"
    "\n"
    "; take-while - return longest prefix satisfying pred\n"
    "(define (take-while pred lst)\n"
    "  (if (or (null? lst) (not (pred (car lst))))\n"
    "      '()\n"
    "      (cons (car lst) (take-while pred (cdr lst)))))\n"
    "\n"
    "; drop-while - drop longest prefix satisfying pred\n"
    "(define (drop-while pred lst)\n"
    "  (cond ((null? lst) '())\n"
    "        ((pred (car lst)) (drop-while pred (cdr lst)))\n"
    "        (else lst)))\n"
    "\n"
    "; span - split at first element not satisfying pred\n"
    "(define (span pred lst)\n"
    "  (values (take-while pred lst) (drop-while pred lst)))\n"
    "\n"
    "; break - split at first element satisfying pred\n"
    "(define (break pred lst)\n"
    "  (span (lambda (x) (not (pred x))) lst))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Deletion\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; delete - remove all elements equal to x\n"
    "(define (delete x lst . maybe-eq)\n"
    "  (let ((eq (if (null? maybe-eq) equal? (car maybe-eq))))\n"
    "    (filter (lambda (y) (not (eq x y))) lst)))\n"
    "\n"
    "; delete-duplicates - remove duplicate elements\n"
    "(define (delete-duplicates lst . maybe-eq)\n"
    "  (let ((eq (if (null? maybe-eq) equal? (car maybe-eq))))\n"
    "    (let loop ((lst lst) (seen '()))\n"
    "      (cond ((null? lst) (reverse seen))\n"
    "            ((find (lambda (y) (eq (car lst) y)) seen)\n"
    "             (loop (cdr lst) seen))\n"
    "            (else (loop (cdr lst) (cons (car lst) seen)))))))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; Additional SRFI-1 Association Lists\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; alist-cons - add entry to front of alist\n"
    "(define (alist-cons key datum alist)\n"
    "  (cons (cons key datum) alist))\n"
    "\n"
    "; alist-copy - shallow copy of alist\n"
    "(define (alist-copy alist)\n"
    "  (map (lambda (pair) (cons (car pair) (cdr pair))) alist))\n"
    "\n"
    "; alist-delete - remove entries matching key\n"
    "(define (alist-delete key alist . maybe-eq)\n"
    "  (let ((eq (if (null? maybe-eq) equal? (car maybe-eq))))\n"
    "    (filter (lambda (pair) (not (eq key (car pair)))) alist)))\n"
    "\n"
    ";;; "
    "=========================================================================="
    "==\n"
    ";;; SRFI-1 Linear Update (Mutation) Procedures\n"
    ";;; "
    "=========================================================================="
    "==\n"
    "\n"
    "; take! - destructive version of take\n"
    "(define (take! lst n)\n"
    "  (cond ((<= n 0) '())\n"
    "        ((null? lst) '())\n"
    "        (else\n"
    "         (let ((tail (list-tail lst (- n 1))))\n"
    "           (if (pair? tail)\n"
    "               (set-cdr! tail '()))\n"
    "           lst))))\n"
    "\n"
    "; drop-right! - destructive version of drop-right\n"
    "(define (drop-right! lst n)\n"
    "  (let ((len (length lst)))\n"
    "    (if (<= (- len n) 0)\n"
    "        '()\n"
    "        (take! lst (- len n)))))\n"
    "\n"
    "; split-at! - destructive version of split-at\n"
    "(define (split-at! lst n)\n"
    "  (if (<= n 0)\n"
    "      (values '() lst)\n"
    "      (let ((tail (drop lst (- n 1))))\n"
    "        (let ((rest (cdr tail)))\n"
    "          (set-cdr! tail '())\n"
    "          (values lst rest)))))\n"
    "\n"
    "; append! - destructive append\n"
    "(define (append! . lists)\n"
    "  (if (null? lists)\n"
    "      '()\n"
    "      (let loop ((result '()) (lists lists))\n"
    "        (cond ((null? lists) result)\n"
    "              ((null? (car lists)) (loop result (cdr lists)))\n"
    "              ((null? result) (loop (car lists) (cdr lists)))\n"
    "              (else\n"
    "               (set-cdr! (last-pair result) (car lists))\n"
    "               (loop result (cdr lists)))))))\n"
    "\n"
    "; concatenate! - destructive concatenate\n"
    "(define (concatenate! list-of-lists)\n"
    "  (apply append! list-of-lists))\n"
    "\n"
    "; reverse! - destructive reverse\n"
    "(define (reverse! lst)\n"
    "  (let loop ((prev '()) (curr lst))\n"
    "    (if (null? curr)\n"
    "        prev\n"
    "        (let ((next (cdr curr)))\n"
    "          (set-cdr! curr prev)\n"
    "          (loop curr next)))))\n"
    "\n"
    "; append-reverse! - destructive append-reverse\n"
    "(define (append-reverse! rev-head tail)\n"
    "  (let loop ((curr rev-head) (acc tail))\n"
    "    (if (null? curr)\n"
    "        acc\n"
    "        (let ((next (cdr curr)))\n"
    "          (set-cdr! curr acc)\n"
    "          (loop next curr)))))\n"
    "\n"
    "; map! - destructive map (mutates first list)\n"
    "(define (map! proc lst . lsts)\n"
    "  (if (null? lsts)\n"
    "      ; Single list case\n"
    "      (let loop ((pair lst))\n"
    "        (if (null? pair)\n"
    "            lst\n"
    "            (begin\n"
    "              (set-car! pair (proc (car pair)))\n"
    "              (loop (cdr pair)))))\n"
    "      ; Multiple lists case\n"
    "      (let loop ((pair lst) (others lsts))\n"
    "        (if (or (null? pair) (any null? others))\n"
    "            lst\n"
    "            (begin\n"
    "              (set-car! pair (apply proc (car pair) (map car others)))\n"
    "              (loop (cdr pair) (map cdr others)))))))\n"
    "\n"
    "; filter! - destructive filter\n"
    "(define (filter! pred lst)\n"
    "  ; Skip leading non-matching elements to find new head\n"
    "  (let find-head ((lst lst))\n"
    "    (cond ((null? lst) '())\n"
    "          ((pred (car lst))\n"
    "           ; Found head, now filter rest in place\n"
    "           (let loop ((prev lst) (curr (cdr lst)))\n"
    "             (cond ((null? curr) lst)\n"
    "                   ((pred (car curr))\n"
    "                    (loop curr (cdr curr)))\n"
    "                   (else\n"
    "                    (set-cdr! prev (cdr curr))\n"
    "                    (loop prev (cdr curr)))))\n"
    "           lst)\n"
    "          (else (find-head (cdr lst))))))\n"
    "\n"
    "; remove! - destructive remove\n"
    "(define (remove! pred lst)\n"
    "  (filter! (lambda (x) (not (pred x))) lst))\n"
    "\n"
    "; partition! - destructive partition\n"
    "(define (partition! pred lst)\n"
    "  (let ((yes (filter! pred (list-copy lst)))\n"
    "        (no (remove! pred lst)))\n"
    "    (values yes no)))\n"
    "\n"
    "; take-while! - destructive take-while\n"
    "(define (take-while! pred lst)\n"
    "  (if (or (null? lst) (not (pred (car lst))))\n"
    "      '()\n"
    "      (let loop ((prev lst) (curr (cdr lst)))\n"
    "        (cond ((null? curr) lst)\n"
    "              ((pred (car curr)) (loop curr (cdr curr)))\n"
    "              (else\n"
    "               (set-cdr! prev '())\n"
    "               lst)))))\n"
    "\n"
    "; span! - destructive span\n"
    "(define (span! pred lst)\n"
    "  (if (or (null? lst) (not (pred (car lst))))\n"
    "      (values '() lst)\n"
    "      (let loop ((prev lst) (curr (cdr lst)))\n"
    "        (cond ((null? curr) (values lst '()))\n"
    "              ((pred (car curr)) (loop curr (cdr curr)))\n"
    "              (else\n"
    "               (set-cdr! prev '())\n"
    "               (values lst curr))))))\n"
    "\n"
    "; break! - destructive break\n"
    "(define (break! pred lst)\n"
    "  (span! (lambda (x) (not (pred x))) lst))\n"
    "\n"
    "; delete! - destructive delete\n"
    "(define (delete! x lst . maybe-eq)\n"
    "  (let ((eq (if (null? maybe-eq) equal? (car maybe-eq))))\n"
    "    (filter! (lambda (y) (not (eq x y))) lst)))\n"
    "\n"
    "; delete-duplicates! - destructive delete-duplicates\n"
    "(define (delete-duplicates! lst . maybe-eq)\n"
    "  (let ((eq (if (null? maybe-eq) equal? (car maybe-eq))))\n"
    "    (let loop ((curr lst))\n"
    "      (if (null? curr)\n"
    "          lst\n"
    "          (begin\n"
    "            (set-cdr! curr (delete! (car curr) (cdr curr) eq))\n"
    "            (loop (cdr curr)))))))\n"
    "\n"
    "; alist-delete! - destructive alist-delete\n"
    "(define (alist-delete! key alist . maybe-eq)\n"
    "  (let ((eq (if (null? maybe-eq) equal? (car maybe-eq))))\n"
    "    (filter! (lambda (pair) (not (eq key (car pair)))) alist)))\n"
    "\n";
static const size_t stdlib_scm_len = sizeof(stdlib_scm) - 1;
