#!/usr/bin/env python3
import sys


def parse_codes(field):
    return [int(part, 16) for part in field.strip().split()]


def emit_array(name, values):
    print(f"static const uint32_t {name}[] = {{")
    for i in range(0, len(values), 8):
        print("    " + ", ".join(f"0x{value:04X}" for value in values[i:i + 8]) + ",")
    print("};")
    print()


def main(argv):
    if len(argv) != 4:
        print("usage: gen_unicode_norm_fixture.py NormalizationTest.txt limit out.h", file=sys.stderr)
        return 2
    path, limit_text, out_path = argv[1:]
    limit = int(limit_text)
    rows = []
    data = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("@"):
                continue
            cols = [part.strip() for part in line.split(";")[:5]]
            if len(cols) != 5:
                continue
            offsets = []
            lengths = []
            for col in cols:
                codes = parse_codes(col)
                offsets.append(len(data))
                lengths.append(len(codes))
                data.extend(codes)
            rows.append((offsets, lengths))
            if len(rows) >= limit:
                break

    with open(out_path, "w", encoding="ascii") as out:
        old_stdout = sys.stdout
        sys.stdout = out
        try:
            print("/* Generated by tools/gen_unicode_norm_fixture.py from Unicode 15.1.0 NormalizationTest.txt. */")
            print("#ifndef UNICODE_NORM_TEST_DATA_H")
            print("#define UNICODE_NORM_TEST_DATA_H")
            print()
            print("#include <stdint.h>")
            print()
            print("typedef struct {")
            print("    uint32_t offset[5];")
            print("    uint16_t length[5];")
            print("} unicode_norm_test_row;")
            print()
            print(f"#define UNICODE_NORM_TEST_ROW_COUNT {len(rows)}")
            print(f"#define UNICODE_NORM_TEST_DATA_COUNT {len(data)}")
            print()
            emit_array("unicode_norm_test_data", data)
            print("static const unicode_norm_test_row unicode_norm_test_rows[] = {")
            for offsets, lengths in rows:
                offsets_text = ", ".join(str(value) for value in offsets)
                lengths_text = ", ".join(str(value) for value in lengths)
                print(f"    {{{{{offsets_text}}}, {{{lengths_text}}}}},")
            print("};")
            print()
            print("#endif")
        finally:
            sys.stdout = old_stdout
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
