#!/usr/bin/env python3
import sys


def parse_code_range(text):
    if ".." in text:
        start, end = text.split("..", 1)
        return range(int(start, 16), int(end, 16) + 1)
    code = int(text, 16)
    return range(code, code + 1)


def parse_unicode_data(path):
    decomps = {}
    combining_classes = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            fields = line.rstrip("\n").split(";")
            if len(fields) < 6:
                continue
            code = int(fields[0], 16)
            ccc = int(fields[3])
            if ccc:
                combining_classes[code] = ccc
            raw = fields[5]
            if raw:
                parts = raw.split()
                compat = False
                if parts[0].startswith("<"):
                    compat = True
                    parts = parts[1:]
                if parts:
                    decomps[code] = (compat, [int(part, 16) for part in parts])
    return decomps, combining_classes


def parse_exclusions(path):
    exclusions = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            exclusions.add(int(line.split()[0], 16))
    return exclusions


def parse_full_composition_exclusions(path):
    exclusions = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line or ";" not in line:
                continue
            code_range, prop = [part.strip() for part in line.split(";", 1)]
            if prop != "Full_Composition_Exclusion":
                continue
            exclusions.update(parse_code_range(code_range))
    return exclusions


def c_array(name, c_type, values, per_line=8):
    print(f"static const {c_type} {name}[] = {{")
    for i in range(0, len(values), per_line):
        print("    " + ", ".join(values[i:i + per_line]) + ",")
    print("};")
    print()


def main(argv):
    if len(argv) != 5:
        print(
            "usage: gen_unicode_norm.py UnicodeData.txt "
            "CompositionExclusions.txt DerivedNormalizationProps.txt out.h",
            file=sys.stderr,
        )
        return 2

    unicode_data, composition_exclusions, derived_props, out_path = argv[1:]
    decomps, combining_classes = parse_unicode_data(unicode_data)
    exclusions = parse_exclusions(composition_exclusions)
    exclusions |= parse_full_composition_exclusions(derived_props)

    decomp_entries = []
    decomp_data = []
    for code, (compat, mapping) in sorted(decomps.items()):
        offset = len(decomp_data)
        decomp_data.extend(mapping)
        decomp_entries.append((code, offset, len(mapping), 1 if compat else 0))

    compose_entries = []
    for code, (compat, mapping) in sorted(decomps.items()):
        if compat or code in exclusions or len(mapping) != 2:
            continue
        starter, combiner = mapping
        if 0xAC00 <= code <= 0xD7A3:
            continue
        compose_entries.append((starter, combiner, code))
    compose_entries.sort()

    ccc_entries = sorted(combining_classes.items())

    with open(out_path, "w", encoding="ascii") as out:
        old_stdout = sys.stdout
        sys.stdout = out
        try:
            print("/* Generated by tools/gen_unicode_norm.py from Unicode 15.1.0 data. */")
            print("#ifndef UNICODE_NORM_TABLES_H")
            print("#define UNICODE_NORM_TABLES_H")
            print()
            print("#include <stdint.h>")
            print()
            print("typedef struct {")
            print("    uint32_t code;")
            print("    uint32_t offset;")
            print("    uint8_t length;")
            print("    uint8_t compatibility;")
            print("} unicode_decomp_entry;")
            print()
            print("typedef struct {")
            print("    uint32_t code;")
            print("    uint8_t combining_class;")
            print("} unicode_ccc_entry;")
            print()
            print("typedef struct {")
            print("    uint32_t starter;")
            print("    uint32_t combiner;")
            print("    uint32_t composite;")
            print("} unicode_compose_entry;")
            print()
            print("#define UNICODE_NORM_VERSION \"15.1.0\"")
            print(f"#define UNICODE_DECOMP_COUNT {len(decomp_entries)}")
            print(f"#define UNICODE_DECOMP_DATA_COUNT {len(decomp_data)}")
            print(f"#define UNICODE_CCC_COUNT {len(ccc_entries)}")
            print(f"#define UNICODE_COMPOSE_COUNT {len(compose_entries)}")
            print()
            c_array("unicode_decomp_data", "uint32_t",
                    [f"0x{code:04X}" for code in decomp_data])
            print("static const unicode_decomp_entry unicode_decomp_table[] = {")
            for code, offset, length, compat in decomp_entries:
                print(f"    {{0x{code:04X}, {offset}, {length}, {compat}}},")
            print("};")
            print()
            print("static const unicode_ccc_entry unicode_ccc_table[] = {")
            for code, ccc in ccc_entries:
                print(f"    {{0x{code:04X}, {ccc}}},")
            print("};")
            print()
            print("static const unicode_compose_entry unicode_compose_table[] = {")
            for starter, combiner, composite in compose_entries:
                print(
                    f"    {{0x{starter:04X}, 0x{combiner:04X}, 0x{composite:04X}}},"
                )
            print("};")
            print()
            print("#endif")
        finally:
            sys.stdout = old_stdout
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
